/**
 * PASHU-RAKSHA Seed Data
 * Source of truth: MH_Livestock_Knowledge_Base_FINAL_v1.md
 * 16 species | 20 breeds | 16 diseases | 33 disease-species associations
 */

// ─── SPECIES (SP_01–SP_16) ─────────────────────────────────────────────────
export const SPECIES_SEED = [
  { id: "SP_01", name: "Cattle",        group: "Bovine",     relevance: "High" },
  { id: "SP_02", name: "Buffalo",       group: "Bovine",     relevance: "High" },
  { id: "SP_03", name: "Goat",          group: "Caprine",    relevance: "High" },
  { id: "SP_04", name: "Sheep",         group: "Ovine",      relevance: "High" },
  { id: "SP_05", name: "Pig",           group: "Porcine",    relevance: "Medium" },
  { id: "SP_06", name: "Horse",         group: "Equine",     relevance: "Medium" },
  { id: "SP_07", name: "Donkey",        group: "Equine",     relevance: "Medium" },
  { id: "SP_08", name: "Pony",          group: "Equine",     relevance: "Low" },
  { id: "SP_09", name: "Mule",          group: "Equine",     relevance: "Low" },
  { id: "SP_10", name: "Camel",         group: "Camelid",    relevance: "Low" },
  { id: "SP_11", name: "Rabbit",        group: "Lagomorph",  relevance: "Low" },
  { id: "SP_12", name: "Chicken",       group: "Poultry",    relevance: "High" },
  { id: "SP_13", name: "Duck",          group: "Poultry",    relevance: "Medium" },
  { id: "SP_14", name: "Turkey",        group: "Poultry",    relevance: "Low" },
  { id: "SP_15", name: "Quail",         group: "Poultry",    relevance: "Low" },
  { id: "SP_16", name: "Other poultry", group: "Poultry",    relevance: "Low" },
];

// ─── BREEDS (BR_01–BR_20) ──────────────────────────────────────────────────
export const BREEDS_SEED = [
  { id: "BR_01", speciesId: "SP_01", name: "Khillar",        type: "Indigenous", status: "Registered" },
  { id: "BR_02", speciesId: "SP_01", name: "Deoni",          type: "Indigenous", status: "Registered" },
  { id: "BR_03", speciesId: "SP_01", name: "Dangi",          type: "Indigenous", status: "Registered" },
  { id: "BR_04", speciesId: "SP_01", name: "Red Kandhari",   type: "Indigenous", status: "Registered" },
  { id: "BR_05", speciesId: "SP_01", name: "Gaolao",         type: "Indigenous", status: "Registered" },
  { id: "BR_06", speciesId: "SP_01", name: "Kathani",        type: "Indigenous", status: "Registered" },
  { id: "BR_07", speciesId: "SP_01", name: "Konkan Kapila",  type: "Indigenous", status: "Registered" },
  { id: "BR_08", speciesId: "SP_01", name: "Umarda",         type: "Indigenous", status: "ICAR-NBAGR accession verified", accession: "INDIA_CATTLE_1100_UMARDA_03059" },
  { id: "BR_09", speciesId: "SP_02", name: "Pandharpuri",    type: "Indigenous", status: "Registered" },
  { id: "BR_10", speciesId: "SP_02", name: "Nagpuri",        type: "Indigenous", status: "Registered" },
  { id: "BR_11", speciesId: "SP_02", name: "Marathwadi",     type: "Indigenous", status: "Registered" },
  { id: "BR_12", speciesId: "SP_02", name: "Purnathadi",     type: "Indigenous", status: "Registered" },
  { id: "BR_13", speciesId: "SP_02", name: "Melghati",       type: "Indigenous", status: "Registered" },
  { id: "BR_14", speciesId: "SP_03", name: "Osmanabadi",     type: "Indigenous", status: "Registered" },
  { id: "BR_15", speciesId: "SP_03", name: "Sangamneri",     type: "Indigenous", status: "Registered" },
  { id: "BR_16", speciesId: "SP_03", name: "Berari",         type: "Indigenous", status: "Registered" },
  { id: "BR_17", speciesId: "SP_03", name: "Konkan Kanyal",  type: "Indigenous", status: "Registered" },
  { id: "BR_18", speciesId: "SP_04", name: "Madgyal",        type: "Indigenous", status: "ICAR-NBAGR accession verified", accession: "INDIA_SHEEP_1108_MADGYAL_14049" },
  { id: "BR_19", speciesId: "SP_04", name: "Deccani",        type: "Indigenous", status: "ICAR-NBAGR register verified",  accession: "INDIA_SHEEP_0111_DECCANI_14021" },
  { id: "BR_20", speciesId: "SP_06", name: "Bhimthadi",      type: "Indigenous", status: "Registered" },
];

// ─── DISEASES (DIS_01–DIS_16) — Full KB fields ──────────────────────────────
export const DISEASES_SEED = [
  {
    id: "DIS_01", name: "Foot and Mouth Disease", shortName: "FMD",
    pathogen: "Aphthovirus", category: "Viral / Infectious", zoonotic: false, notifiable: true,
    incubation: "2–14 days",
    transmission: "Highly contagious; direct contact, contaminated equipment, air over short distances.",
    exposureTypes: ["Direct contact", "Fomites", "Livestock movement"],
    seasonality: "Year-round; risk increases during fairs/markets and animal movement.",
    environmentalRisk: "Low environmental persistence; mainly animal-to-animal.",
    earlySymptoms: "Fever, vesicular lesions on mouth/feet, excess salivation, lameness.",
    behavioralSigns: "Reduced feeding, reluctance to move, isolation from herd.",
    physicalSigns: "Blisters on tongue/gums/hooves, drooling, limping.",
    physiologicalSigns: "Pyrexia, reduced milk yield.",
    mortality: "Low in adults; higher in young animals.",
    productivityImpact: "Significant milk yield reduction, weight loss.",
    cameraSignals: "Reduced movement, lameness/gait change, isolation.",
    cameraDetectabilityClass: "Moderate",
    iotSignals: "Activity drop, feeding drop, elevated temperature trend.",
    iotDetectabilityClass: "Moderate",
    farmerSignals: "Drooling, limping, sores visible in mouth.",
    diagnostics: "Clinical exam and laboratory confirmation (e.g., RT-PCR/ELISA) by an accredited veterinary lab.",
    sample: "Vesicular fluid, epithelial tissue.",
    vaccination: "Biannual FMD vaccination as per state schedule.",
    prevention: "Vaccination, movement control, disinfection at farm entry points.",
    control: "Movement restrictions, stamping out in some protocols.",
    containment: "Isolate suspected animals, restrict movement, notify veterinary authority.",
    aiFeatures: ["Gait analysis", "Activity monitoring", "Feeding pattern deviation"],
    surveillancePriority: "High",
    maharashtraEvidence: "Endemic risk reported in multiple districts; state runs periodic vaccination drives.",
    evidenceStatus: "Confirmed",
  },
  {
    id: "DIS_02", name: "Haemorrhagic Septicaemia", shortName: "HS",
    pathogen: "Pasteurella multocida", category: "Bacterial / Infectious", zoonotic: false, notifiable: true,
    incubation: "1–3 days",
    transmission: "Inhalation, ingestion, contaminated water/feed; indirect environmental transmission.",
    exposureTypes: ["Indirect environmental", "Shared water"],
    seasonality: "Monsoon season (June–September); stress increases susceptibility.",
    environmentalRisk: "Wet/humid conditions, stress from monsoon-related factors.",
    earlySymptoms: "High fever, swelling of head/neck, respiratory distress.",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Edema of throat/brisket, profuse salivation.",
    physiologicalSigns: "Pyrexia, rapid respiration.",
    mortality: "High if untreated; can be peracute.",
    productivityImpact: "Severe; often fatal before treatment possible.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Sudden high fever, neck swelling, severe breathing difficulty.",
    diagnostics: "Blood smear, bacterial culture.",
    sample: "Blood, nasal discharge.",
    vaccination: "Annual vaccination before monsoon.",
    prevention: "Vaccination, good hygiene.",
    control: "Antibiotic treatment (early); supportive care.",
    containment: "Isolate, disinfect, treat with antibiotics.",
    aiFeatures: ["Activity monitoring", "Recumbency detection"],
    surveillancePriority: "High",
    maharashtraEvidence: "Not established in consulted source.",
    evidenceStatus: "Not established in consulted source.",
  },
  {
    id: "DIS_03", name: "Lumpy Skin Disease", shortName: "LSD",
    pathogen: "Capripoxvirus", category: "Viral / Infectious", zoonotic: false, notifiable: true,
    incubation: "4–14 days",
    transmission: "Vector-borne (biting flies, ticks, mosquitoes); indirect contact possible.",
    exposureTypes: ["Vector-borne insects"],
    seasonality: "Warmer months; wet season when vectors are active.",
    environmentalRisk: "High vector density, proximity to standing water.",
    earlySymptoms: "Fever, nodular skin lesions, reduced milk yield, lymph node swelling.",
    behavioralSigns: "Lethargy, reduced feeding, isolation.",
    physicalSigns: "Firm circumscribed skin nodules, ocular/nasal discharge.",
    physiologicalSigns: "Fever, reduced milk production.",
    mortality: "Low; significant morbidity.",
    productivityImpact: "Milk yield reduction, hide damage, weight loss.",
    cameraSignals: "Visible skin lesions, reduced movement, isolation.",
    cameraDetectabilityClass: "Moderate",
    iotSignals: "Temperature rise, activity and feeding drop.",
    iotDetectabilityClass: "Moderate",
    farmerSignals: "Lumps/nodules on skin, fever, reduced milk.",
    diagnostics: "Clinical exam plus laboratory confirmation (e.g., PCR) by an accredited veterinary lab.",
    sample: "Skin biopsy, blood.",
    vaccination: "LSD vaccination as per state animal husbandry guidance.",
    prevention: "Vector control, vaccination, quarantine of new/sick animals.",
    control: "Supportive care; vector control around farm.",
    containment: "Isolate affected animals, vector control around farm, notify authority.",
    aiFeatures: ["Skin lesion detection", "Activity monitoring", "Temperature trending"],
    surveillancePriority: "High",
    maharashtraEvidence: "Periodic outbreaks reported in Maharashtra districts in recent years.",
    evidenceStatus: "Confirmed",
  },
  {
    id: "DIS_04", name: "Brucellosis", shortName: "Brucellosis",
    pathogen: "Brucella abortus", category: "Bacterial / Infectious", zoonotic: true, notifiable: true,
    incubation: "2–4 weeks (variable)",
    transmission: "Contact with birth fluids/aborted material; contaminated feed/water.",
    exposureTypes: ["Direct contact", "Exact additional risk factors not established"],
    seasonality: "Not established in consulted source.",
    environmentalRisk: "Not established in consulted source.",
    earlySymptoms: "Abortion in late pregnancy, retained placenta, reduced fertility.",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Reproductive discharge, occasional joint swelling.",
    physiologicalSigns: "Reproductive failure.",
    mortality: "Low; significant reproductive impact.",
    productivityImpact: "Reduced fertility, abortions, reduced calving rates.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Abortion in late pregnancy, retained afterbirth.",
    diagnostics: "Milk Ring Test / ELISA (serological testing by an accredited veterinary/public-health laboratory).",
    sample: "Blood serum, milk.",
    vaccination: "Brucellosis vaccination for female calves as per state programme.",
    prevention: "Vaccination, hygienic handling of birth material, testing of breeding stock.",
    control: "Test-and-cull in national programme.",
    containment: "Isolate affected animal, safe disposal of aborted material, notify authority (zoonotic risk).",
    aiFeatures: ["Reproductive event tracking", "Behavioral monitoring"],
    surveillancePriority: "High",
    maharashtraEvidence: "Included under national brucellosis control programme.",
    evidenceStatus: "Confirmed",
  },
  {
    id: "DIS_05", name: "Leptospirosis", shortName: "Leptospirosis",
    pathogen: "Leptospira spp.", category: "Bacterial / Infectious", zoonotic: true, notifiable: false,
    incubation: "2–30 days",
    transmission: "Urine-contaminated water/soil; environmental/water.",
    exposureTypes: ["Environmental/water"],
    seasonality: "Monsoon and post-monsoon; linked to flooding.",
    environmentalRisk: "Standing water, flooding, rodent presence.",
    earlySymptoms: "Fever, jaundice, abortion, red urine.",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Not established in consulted source.",
    physiologicalSigns: "Haemoglobinuria, jaundice.",
    mortality: "Moderate; varies by serovar.",
    productivityImpact: "Milk drop, abortions.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Red/dark urine, jaundice, sudden abortion.",
    diagnostics: "Serology, PCR.",
    sample: "Blood, urine.",
    vaccination: "Vaccination in endemic areas.",
    prevention: "Rodent control, clean water.",
    control: "Antibiotic treatment.",
    containment: "Isolate, treat with antibiotics.",
    aiFeatures: ["Water exposure risk scoring"],
    surveillancePriority: "Medium",
    maharashtraEvidence: "Not established in consulted source.",
    evidenceStatus: "Not established in consulted source.",
  },
  {
    id: "DIS_06", name: "Peste des petits ruminants", shortName: "PPR",
    pathogen: "Morbillivirus", category: "Viral / Infectious", zoonotic: false, notifiable: true,
    incubation: "3–6 days",
    transmission: "Highly contagious via direct contact and respiratory droplets.",
    exposureTypes: ["Direct contact", "Grazing", "Movement"],
    seasonality: "Year-round; dry season congregation increases spread.",
    environmentalRisk: "Close housing, mixed flock movement.",
    earlySymptoms: "Fever, oculonasal discharge, mouth erosions, diarrhoea.",
    behavioralSigns: "Depression, reduced feeding, huddling/isolation.",
    physicalSigns: "Discharge from eyes/nose, mouth lesions, laboured breathing.",
    physiologicalSigns: "Pyrexia, dehydration.",
    mortality: "High in susceptible populations (up to 90%).",
    productivityImpact: "Severe losses in goats/sheep flocks.",
    cameraSignals: "Isolation, reduced movement, visible discharge (limited camera reliability).",
    cameraDetectabilityClass: "Low",
    iotSignals: "Feeding drop, activity drop, temperature rise.",
    iotDetectabilityClass: "Moderate",
    farmerSignals: "Runny nose and eyes, mouth sores, diarrhoea, huddling.",
    diagnostics: "c-ELISA / s-ELISA (laboratory confirmation by an accredited veterinary lab).",
    sample: "Nasal/ocular swabs, blood.",
    vaccination: "PPR vaccination as per national control programme schedule.",
    prevention: "Vaccination, quarantine of new animals, flock biosecurity.",
    control: "Mass vaccination, isolation, herd/ring vaccination.",
    containment: "Isolate suspected animals, restrict flock movement, notify authority.",
    aiFeatures: ["Discharge detection", "Activity monitoring", "Cluster detection"],
    surveillancePriority: "High",
    maharashtraEvidence: "Covered under national PPR control programme in the state.",
    evidenceStatus: "Confirmed",
  },
  {
    id: "DIS_07", name: "Glanders", shortName: "Glanders",
    pathogen: "Burkholderia mallei", category: "Bacterial / Infectious", zoonotic: true, notifiable: true,
    incubation: "1–14 days",
    transmission: "Shared feed/water, equine congregation, contact with respiratory secretions.",
    exposureTypes: ["Shared feed/water", "Equine congregation"],
    seasonality: "Not established in consulted source.",
    environmentalRisk: "Not established in consulted source.",
    earlySymptoms: "Nasal discharge, ulcers, nodules on skin.",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Nasal/respiratory signs, nodules.",
    physiologicalSigns: "Not established in consulted source.",
    mortality: "High in acute form; chronic form possible.",
    productivityImpact: "Severe; notifiable and requires stamping out.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Nasal discharge, skin nodules, laboured breathing.",
    diagnostics: "Complement Fixation Test; Mallein test, serology.",
    sample: "Nasal discharge, blood.",
    vaccination: "None.",
    prevention: "Testing and elimination; disinfection, surveillance/infected zones.",
    control: "Statutory containment.",
    containment: "Strict quarantine, euthanasia of positive cases.",
    aiFeatures: ["Nasal/respiratory signal monitoring"],
    surveillancePriority: "High",
    maharashtraEvidence: "Not established in consulted source.",
    evidenceStatus: "Not established in consulted source.",
  },
  {
    id: "DIS_08", name: "African Swine Fever", shortName: "ASF",
    pathogen: "Asfivirus", category: "Viral / Infectious", zoonotic: false, notifiable: true,
    incubation: "4–19 days",
    transmission: "Direct contact, contaminated fomites, soft ticks, wild-boar interface.",
    exposureTypes: ["Fomites", "Direct contact", "Wild-boar interface"],
    seasonality: "Not established in consulted source.",
    environmentalRisk: "Not established in consulted source.",
    earlySymptoms: "High fever, loss of appetite, hemorrhages on skin.",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Not established in consulted source.",
    physiologicalSigns: "Pyrexia, haemorrhage.",
    mortality: "Near 100% in acute form.",
    productivityImpact: "Total flock loss risk.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Sudden deaths, high fever, skin redness.",
    diagnostics: "Real-time PCR.",
    sample: "Blood, tissue.",
    vaccination: "None.",
    prevention: "Strict biosecurity, regional restrictions.",
    control: "Containment/culling.",
    containment: "Culling, quarantine.",
    aiFeatures: ["Huddling/activity/temperature monitoring"],
    surveillancePriority: "High",
    maharashtraEvidence: "Not established in consulted source.",
    evidenceStatus: "Not established in consulted source.",
  },
  {
    id: "DIS_09", name: "Rabies", shortName: "Rabies",
    pathogen: "Lyssavirus", category: "Viral / Infectious", zoonotic: true, notifiable: true,
    incubation: "3 weeks – 3 months",
    transmission: "Bite from infected animal; wildlife-dog exposure.",
    exposureTypes: ["Bites", "Wildlife-dog exposure"],
    seasonality: "Year-round.",
    environmentalRisk: "Proximity to stray dogs, wildlife corridors.",
    earlySymptoms: "Behavioral changes, paralysis, excessive salivation.",
    behavioralSigns: "Aggression or extreme lethargy, restlessness.",
    physicalSigns: "Not established in consulted source.",
    physiologicalSigns: "Progressive paralysis.",
    mortality: "Near 100% once clinical signs appear.",
    productivityImpact: "Not applicable (fatal).",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Sudden behavioral change, aggression, drooling.",
    diagnostics: "Post-mortem brain examination (DFA test).",
    sample: "Brain tissue (post-mortem).",
    vaccination: "Pre and post exposure vaccination.",
    prevention: "Vaccination of pets/livestock.",
    control: "Post-exposure prophylaxis for humans.",
    containment: "Euthanasia, notify authorities.",
    aiFeatures: ["Behavioral anomaly detection"],
    surveillancePriority: "High",
    maharashtraEvidence: "Not established in consulted source.",
    evidenceStatus: "Not established in consulted source.",
  },
  {
    id: "DIS_10", name: "Black Quarter", shortName: "BQ",
    pathogen: "Clostridium chauvoei", category: "Bacterial / Infectious", zoonotic: false, notifiable: true,
    incubation: "Hours to days",
    transmission: "Ingestion of spores; soil/environmental spores.",
    exposureTypes: ["Soil/environmental spores"],
    seasonality: "Monsoon and post-monsoon when soil disturbed.",
    environmentalRisk: "Spore-contaminated soil; young animals grazing.",
    earlySymptoms: "Sudden onset of fever, lameness, swelling of heavy muscles.",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Crepitating swellings on hindquarters.",
    physiologicalSigns: "Pyrexia, toxaemia.",
    mortality: "Very high; often peracute.",
    productivityImpact: "Death of productive animals.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Sudden lameness, swollen hindquarters, rapid deterioration.",
    diagnostics: "Clinical signs, smear.",
    sample: "Muscle tissue.",
    vaccination: "Annual vaccination.",
    prevention: "Vaccination.",
    control: "Penicillin (early); rarely effective due to rapid course.",
    containment: "Proper carcass disposal.",
    aiFeatures: ["Activity drop", "Lameness detection"],
    surveillancePriority: "Medium",
    maharashtraEvidence: "Not established in consulted source.",
    evidenceStatus: "Not established in consulted source.",
  },
  {
    id: "DIS_11", name: "Anthrax", shortName: "Anthrax",
    pathogen: "Bacillus anthracis", category: "Bacterial / Infectious", zoonotic: true, notifiable: true,
    incubation: "1–5 days",
    transmission: "Spore exposure via soil, contaminated feed; carcasses highly infectious.",
    exposureTypes: ["Soil/environmental spores"],
    seasonality: "Dry season in endemic zones; post-flood when soil disturbed.",
    environmentalRisk: "Grazing on known endemic soil/pasture.",
    earlySymptoms: "Sudden death, high fever, bleeding from body openings in acute cases.",
    behavioralSigns: "Severe depression, collapse.",
    physicalSigns: "Unclotted blood discharge, rapid deterioration.",
    physiologicalSigns: "Septicaemia, toxaemia.",
    mortality: "Near 100% in peracute form.",
    productivityImpact: "Not applicable (fatal).",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Sudden severe activity drop preceding collapse (limited data).",
    iotDetectabilityClass: "Low",
    farmerSignals: "Sudden death, bloody discharge, rapid collapse.",
    diagnostics: "Laboratory confirmation required; carcass must not be opened in field — notify authority immediately.",
    sample: "Blood from peripheral vessel (pre-mortem); do not open carcass.",
    vaccination: "Anthrax vaccination in known endemic zones per state schedule.",
    prevention: "Vaccination in endemic zones, safe carcass disposal, restricted grazing on risk sites.",
    control: "Penicillin (prophylactic in exposed animals).",
    containment: "Immediate notification to veterinary/public-health authority; movement and carcass control (zoonotic risk).",
    aiFeatures: ["Sudden activity drop detection"],
    surveillancePriority: "High",
    maharashtraEvidence: "Sporadic cases reported in specific endemic pockets historically.",
    evidenceStatus: "Confirmed",
  },
  {
    id: "DIS_12", name: "Japanese Encephalitis", shortName: "JE",
    pathogen: "Flavivirus", category: "Viral / Vector-borne", zoonotic: true, notifiable: true,
    incubation: "4–14 days",
    transmission: "Mosquito vectors; pigs as amplifying host.",
    exposureTypes: ["Mosquito-borne", "Pigs as amplifying host"],
    seasonality: "Monsoon and post-monsoon; peak vector activity.",
    environmentalRisk: "Proximity to rice paddies, standing water, pig farms.",
    earlySymptoms: "Fever, neurological signs (in horses), reproductive failure (in pigs).",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Not established in consulted source.",
    physiologicalSigns: "Encephalitis in horses; abortion in pigs.",
    mortality: "High in horses with neurological signs.",
    productivityImpact: "Reproductive failure in pigs; mortality in horses.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Reproductive failure in pigs; neurological signs in horses.",
    diagnostics: "Serology (IgM ELISA).",
    sample: "Blood, CSF.",
    vaccination: "Vaccination in some endemic areas.",
    prevention: "Vector control.",
    control: "Supportive care; vector control.",
    containment: "Vector control.",
    aiFeatures: ["Neurological behavior monitoring"],
    surveillancePriority: "Medium",
    maharashtraEvidence: "Not established in consulted source.",
    evidenceStatus: "Not established in consulted source.",
  },
  {
    id: "DIS_13", name: "Babesiosis", shortName: "Babesiosis",
    pathogen: "Babesia spp.", category: "Parasitic / Vector-borne", zoonotic: false, notifiable: false,
    incubation: "7–21 days",
    transmission: "Tick-borne.",
    exposureTypes: ["Tick-borne"],
    seasonality: "Active tick season; warmer months.",
    environmentalRisk: "Tick-infested grazing areas; poor tick control.",
    earlySymptoms: "Fever, anemia, hemoglobinuria (red water).",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Not established in consulted source.",
    physiologicalSigns: "Haemolytic anaemia, haemoglobinuria.",
    mortality: "Moderate; higher in exotic/crossbred cattle.",
    productivityImpact: "Milk drop, weakness, weight loss.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Red/dark urine, weakness, pale gums.",
    diagnostics: "Giemsa-stained blood smear; PCR; IFAT/ELISA.",
    sample: "Blood smear.",
    vaccination: "No commercial vaccine in India in the consulted source set.",
    prevention: "Tick control / integrated acaricide management.",
    control: "Babesiacidal treatment.",
    containment: "Tick control, treat with babesiacides.",
    aiFeatures: ["Activity/temperature-related abnormality monitoring"],
    surveillancePriority: "Medium",
    maharashtraEvidence: "Confirmed in supplied evidence set.",
    evidenceStatus: "Confirmed in supplied evidence set.",
  },
  {
    id: "DIS_14", name: "Theileriosis", shortName: "Theileriosis",
    pathogen: "Theileria spp.", category: "Parasitic / Vector-borne", zoonotic: false, notifiable: false,
    incubation: "8–30 days",
    transmission: "Tick-borne, including Hyalomma anatolicum.",
    exposureTypes: ["Tick-borne"],
    seasonality: "Tick season.",
    environmentalRisk: "Exotic/crossbred cattle highly susceptible; tick-infested areas.",
    earlySymptoms: "Fever, enlarged lymph nodes, anemia.",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Not established in consulted source.",
    physiologicalSigns: "Anaemia, lymph node enlargement.",
    mortality: "High in susceptible breeds.",
    productivityImpact: "Significant milk and production losses.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Enlarged lymph nodes (particularly parotid), pale gums, fever.",
    diagnostics: "Giemsa-stained blood smear; PCR; Plate/Dot-ELISA.",
    sample: "Blood smear, lymph node biopsy.",
    vaccination: "Raksha Vac-T (referenced in supplied evidence).",
    prevention: "Tick control.",
    control: "Buparvaquone (referenced treatment in supplied evidence).",
    containment: "Treat with buparvaquone.",
    aiFeatures: ["Activity/temperature monitoring"],
    surveillancePriority: "Medium",
    maharashtraEvidence: "Confirmed in supplied evidence set.",
    evidenceStatus: "Confirmed in supplied evidence set.",
  },
  {
    id: "DIS_15", name: "Trypanosomiasis (Surra)", shortName: "Surra",
    pathogen: "Trypanosoma evansi", category: "Parasitic / Vector-borne", zoonotic: false, notifiable: false,
    incubation: "1–4 weeks",
    transmission: "Mechanically transmitted by biting flies (Tabanidae).",
    exposureTypes: ["Mechanical transmission by biting flies"],
    seasonality: "Fly season; warmer months.",
    environmentalRisk: "High biting fly density; livestock congregation.",
    earlySymptoms: "Fever, progressive anemia, weakness, circling.",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Not established in consulted source.",
    physiologicalSigns: "Progressive anaemia; can be fatal in horses.",
    mortality: "Can be fatal in horses; moderate in cattle/buffalo.",
    productivityImpact: "Weight loss, weakness, reduced productivity.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Progressive weakness, weight loss, intermittent fever.",
    diagnostics: "Giemsa-stained thin blood smear; CATT/T. evansi; PCR.",
    sample: "Blood smear.",
    vaccination: "No vaccine because of antigenic variation.",
    prevention: "Fly control.",
    control: "Trypanocidal drug classes (information in supplied evidence).",
    containment: "Trypanocidal drugs.",
    aiFeatures: ["Activity/body-condition monitoring (supportive)"],
    surveillancePriority: "Medium",
    maharashtraEvidence: "India-relevant; Maharashtra-specific animal-level evidence not established.",
    evidenceStatus: "India-relevant; Maharashtra-specific evidence not established.",
  },
  {
    id: "DIS_16", name: "Enterotoxaemia", shortName: "Enterotoxaemia",
    pathogen: "Clostridium perfringens", category: "Bacterial / Infectious", zoonotic: false, notifiable: false,
    incubation: "Hours",
    transmission: "Abrupt diet/feed change triggers toxin production.",
    exposureTypes: ["Abrupt diet/feed change"],
    seasonality: "Post-monsoon (lush grazing); any time of diet change.",
    environmentalRisk: "Sudden change to rich/lush diet.",
    earlySymptoms: "Sudden death, convulsions, diarrhea.",
    behavioralSigns: "Not established in consulted source.",
    physicalSigns: "Not established in consulted source.",
    physiologicalSigns: "Toxaemia, sudden death.",
    mortality: "High; often sudden.",
    productivityImpact: "Sudden livestock loss.",
    cameraSignals: "Not established in consulted source.",
    cameraDetectabilityClass: "Low",
    iotSignals: "Not established in consulted source.",
    iotDetectabilityClass: "Low",
    farmerSignals: "Sudden death after diet change; convulsions.",
    diagnostics: "Post-mortem, toxin detection.",
    sample: "Intestinal content.",
    vaccination: "Annual vaccination.",
    prevention: "Gradual diet changes, vaccination.",
    control: "Antitoxin if possible.",
    containment: "Isolate, treat with antitoxin if possible.",
    aiFeatures: ["Sudden activity drop detection"],
    surveillancePriority: "Medium",
    maharashtraEvidence: "Not established in consulted source.",
    evidenceStatus: "Not established in consulted source.",
  },
];

// ─── DISEASE-SPECIES ASSOCIATIONS (33 records) ──────────────────────────────
export const DISEASE_SPECIES_SEED = [
  // FMD (DIS_01) — Cattle, Buffalo, Goat, Sheep, Pig
  { id: "REC_01", diseaseId: "DIS_01", speciesId: "SP_01", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_02", diseaseId: "DIS_01", speciesId: "SP_02", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_03", diseaseId: "DIS_01", speciesId: "SP_03", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_04", diseaseId: "DIS_01", speciesId: "SP_04", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_05", diseaseId: "DIS_01", speciesId: "SP_05", breedNote: "All", evidence: "Confirmed" },
  // HS (DIS_02) — Cattle, Buffalo
  { id: "REC_06", diseaseId: "DIS_02", speciesId: "SP_01", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_07", diseaseId: "DIS_02", speciesId: "SP_02", breedNote: "All", evidence: "Confirmed" },
  // LSD (DIS_03) — Cattle, Buffalo
  { id: "REC_08", diseaseId: "DIS_03", speciesId: "SP_01", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_09", diseaseId: "DIS_03", speciesId: "SP_02", breedNote: "All", evidence: "Confirmed" },
  // Brucellosis (DIS_04) — Cattle, Buffalo
  { id: "REC_10", diseaseId: "DIS_04", speciesId: "SP_01", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_11", diseaseId: "DIS_04", speciesId: "SP_02", breedNote: "All", evidence: "Confirmed" },
  // Leptospirosis (DIS_05) — Cattle, Buffalo
  { id: "REC_12", diseaseId: "DIS_05", speciesId: "SP_01", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_13", diseaseId: "DIS_05", speciesId: "SP_02", breedNote: "All", evidence: "Confirmed" },
  // PPR (DIS_06) — Goat, Sheep
  { id: "REC_14", diseaseId: "DIS_06", speciesId: "SP_03", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_15", diseaseId: "DIS_06", speciesId: "SP_04", breedNote: "All", evidence: "Confirmed" },
  // Glanders (DIS_07) — Horse, Donkey, Pony, Mule
  { id: "REC_16", diseaseId: "DIS_07", speciesId: "SP_06", breedNote: "Bhimthadi / All", evidence: "Confirmed" },
  { id: "REC_17", diseaseId: "DIS_07", speciesId: "SP_07", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_18", diseaseId: "DIS_07", speciesId: "SP_08", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_19", diseaseId: "DIS_07", speciesId: "SP_09", breedNote: "All", evidence: "Confirmed" },
  // ASF (DIS_08) — Pig
  { id: "REC_20", diseaseId: "DIS_08", speciesId: "SP_05", breedNote: "All", evidence: "Confirmed" },
  // Rabies (DIS_09) — Cattle, Buffalo
  { id: "REC_21", diseaseId: "DIS_09", speciesId: "SP_01", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_22", diseaseId: "DIS_09", speciesId: "SP_02", breedNote: "All", evidence: "Confirmed" },
  // Black Quarter (DIS_10) — Cattle
  { id: "REC_23", diseaseId: "DIS_10", speciesId: "SP_01", breedNote: "All", evidence: "Confirmed" },
  // Anthrax (DIS_11) — Cattle, Sheep
  { id: "REC_24", diseaseId: "DIS_11", speciesId: "SP_01", breedNote: "All", evidence: "Confirmed" },
  { id: "REC_25", diseaseId: "DIS_11", speciesId: "SP_04", breedNote: "All", evidence: "Confirmed" },
  // JE (DIS_12) — Pig
  { id: "REC_26", diseaseId: "DIS_12", speciesId: "SP_05", breedNote: "All", evidence: "Confirmed" },
  // Babesiosis (DIS_13) — Cattle, Buffalo [NEW REC_27, REC_28]
  { id: "REC_27", diseaseId: "DIS_13", speciesId: "SP_01", breedNote: "Indigenous / crossbred", evidence: "Confirmed in supplied evidence set" },
  { id: "REC_28", diseaseId: "DIS_13", speciesId: "SP_02", breedNote: "All", evidence: "Confirmed in supplied evidence set" },
  // Theileriosis (DIS_14) — Cattle, Buffalo [NEW REC_29, REC_30]
  { id: "REC_29", diseaseId: "DIS_14", speciesId: "SP_01", breedNote: "Indigenous / crossbred", evidence: "Confirmed in supplied evidence set" },
  { id: "REC_30", diseaseId: "DIS_14", speciesId: "SP_02", breedNote: "All", evidence: "Confirmed in supplied evidence set" },
  // Trypanosomiasis/Surra (DIS_15) — Cattle, Buffalo, Horse [NEW REC_31, REC_32, REC_33]
  { id: "REC_31", diseaseId: "DIS_15", speciesId: "SP_01", breedNote: "All", evidence: "India-relevant; Maharashtra-specific animal-level evidence not established" },
  { id: "REC_32", diseaseId: "DIS_15", speciesId: "SP_02", breedNote: "All", evidence: "India-relevant; Maharashtra-specific evidence not established" },
  { id: "REC_33", diseaseId: "DIS_15", speciesId: "SP_06", breedNote: "All", evidence: "India-relevant; Maharashtra-specific evidence not established" },
];

// ─── USERS ──────────────────────────────────────────────────────────────────
export const USERS_SEED = [
  { id: "USR_01", name: "R. Deshmukh",   role: "farmer",   district: "Nashik",   farmId: "FARM_A", avatar: "R" },
  { id: "USR_02", name: "S. Patil",       role: "farmer",   district: "Pune",     farmId: "FARM_B", avatar: "S" },
  { id: "USR_03", name: "Dr. A. Kulkarni",role: "vet",      district: "Nashik",   farmId: null,     avatar: "A" },
  { id: "USR_04", name: "Dr. M. Shinde",  role: "vet",      district: "Nagpur",   farmId: null,     avatar: "M" },
  { id: "USR_05", name: "Collector Singh",role: "official", district: "State",    farmId: null,     avatar: "C" },
  { id: "USR_06", name: "Field Officer T",role: "field",    district: "Nashik",   farmId: null,     avatar: "T" },
  { id: "USR_07", name: "Admin",          role: "admin",    district: "State",    farmId: null,     avatar: "Ad"},
];

// ─── FARMS ──────────────────────────────────────────────────────────────────
export const FARMS_SEED = [
  { id: "FARM_A", name: "Deshmukh Dairy",             district: "Nashik",           village: "Niphad",    lat: 20.08, lng: 73.78, contact: "R. Deshmukh",    phone: "9876543210" },
  { id: "FARM_B", name: "Patil Livestock",             district: "Pune",             village: "Baramati",  lat: 18.15, lng: 74.57, contact: "S. Patil",        phone: "9876543211" },
  { id: "FARM_C", name: "Jadhav Sheep & Goat Unit",   district: "Kolhapur",         village: "Karvir",    lat: 16.70, lng: 74.23, contact: "A. Jadhav",       phone: "9876543212" },
  { id: "FARM_D", name: "Rathi Buffalo Farm",          district: "Nagpur",           village: "Kamptee",   lat: 21.21, lng: 79.18, contact: "M. Rathi",        phone: "9876543213" },
  { id: "FARM_E", name: "Kadam Gaushala",              district: "Chh. Sambhajinagar", village: "Gangapur", lat: 19.88, lng: 75.34, contact: "V. Kadam",     phone: "9876543214" },
];

// ─── ANIMALS (12 demo animals) ───────────────────────────────────────────────
function daysAgo(n) { return new Date(Date.now() - n * 86400000).toISOString(); }

export const ANIMALS_SEED = [
  // Farm A — Nashik
  {
    id: "MH-CAT-027", tagId: "MH-CAT-027", farmId: "FARM_A", speciesId: "SP_01", breedId: "BR_01",
    name: "Kamdhenu", age: 4, sex: "Female", weight: 320, dob: "2022-05-10",
    registeredAt: daysAgo(400),
    baseline: { activity: 92, feeding: 88, movement: 85, rumination: 78 },
    current:  { activity: 52, feeding: 45, movement: 40, rumination: 30, tempTrend: "elevated", social: "isolating" },
    lastObservation: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "MH-CAT-031", tagId: "MH-CAT-031", farmId: "FARM_A", speciesId: "SP_01", breedId: "BR_02",
    name: "Ganga", age: 3, sex: "Female", weight: 285, dob: "2023-02-14",
    registeredAt: daysAgo(350),
    baseline: { activity: 90, feeding: 86, movement: 88, rumination: 84 },
    current:  { activity: 80, feeding: 79, movement: 81, rumination: 80, tempTrend: "normal", social: "normal" },
    lastObservation: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "MH-CAT-014", tagId: "MH-CAT-014", farmId: "FARM_A", speciesId: "SP_01", breedId: "BR_04",
    name: "Lakshmi", age: 5, sex: "Female", weight: 340, dob: "2021-07-22",
    registeredAt: daysAgo(500),
    baseline: { activity: 88, feeding: 85, movement: 87, rumination: 82 },
    current:  { activity: 84, feeding: 83, movement: 85, rumination: 80, tempTrend: "normal", social: "normal" },
    lastObservation: new Date(Date.now() - 18000000).toISOString(),
  },
  // Farm B — Pune
  {
    id: "MH-CAT-063", tagId: "MH-CAT-063", farmId: "FARM_B", speciesId: "SP_01", breedId: "BR_05",
    name: "Savitri", age: 4, sex: "Female", weight: 310, dob: "2022-09-18",
    registeredAt: daysAgo(380),
    baseline: { activity: 93, feeding: 91, movement: 90, rumination: 87 },
    current:  { activity: 91, feeding: 89, movement: 88, rumination: 85, tempTrend: "normal", social: "normal" },
    lastObservation: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "MH-CAT-078", tagId: "MH-CAT-078", farmId: "FARM_B", speciesId: "SP_01", breedId: "BR_03",
    name: "Yamuna", age: 5, sex: "Female", weight: 325, dob: "2021-03-08",
    registeredAt: daysAgo(460),
    baseline: { activity: 90, feeding: 88, movement: 89, rumination: 84 },
    current:  { activity: 66, feeding: 70, movement: 68, rumination: 71, tempTrend: "normal", social: "normal" },
    lastObservation: new Date(Date.now() - 14400000).toISOString(),
  },
  // Farm C — Kolhapur
  {
    id: "MH-GOT-102", tagId: "MH-GOT-102", farmId: "FARM_C", speciesId: "SP_03", breedId: "BR_14",
    name: "Pari", age: 2, sex: "Female", weight: 32, dob: "2024-01-20",
    registeredAt: daysAgo(280),
    baseline: { activity: 91, feeding: 90, movement: 89, rumination: 88 },
    current:  { activity: 70, feeding: 68, movement: 72, rumination: 74, tempTrend: "normal", social: "normal" },
    lastObservation: new Date(Date.now() - 21600000).toISOString(),
  },
  {
    id: "MH-SHP-055", tagId: "MH-SHP-055", farmId: "FARM_C", speciesId: "SP_04", breedId: "BR_19",
    name: "Badal", age: 3, sex: "Male", weight: 42, dob: "2023-04-10",
    registeredAt: daysAgo(310),
    baseline: { activity: 89, feeding: 87, movement: 90, rumination: 85 },
    current:  { activity: 88, feeding: 86, movement: 89, rumination: 84, tempTrend: "normal", social: "normal" },
    lastObservation: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: "MH-SHP-061", tagId: "MH-SHP-061", farmId: "FARM_C", speciesId: "SP_04", breedId: "BR_18",
    name: "Bhola", age: 2, sex: "Male", weight: 38, dob: "2024-03-15",
    registeredAt: daysAgo(200),
    baseline: { activity: 92, feeding: 88, movement: 91, rumination: 86 },
    current:  { activity: 75, feeding: 72, movement: 70, rumination: 68, tempTrend: "elevated", social: "isolating" },
    lastObservation: new Date(Date.now() - 5400000).toISOString(),
  },
  // Farm D — Nagpur
  {
    id: "MH-BUF-009", tagId: "MH-BUF-009", farmId: "FARM_D", speciesId: "SP_02", breedId: "BR_10",
    name: "Kali", age: 6, sex: "Female", weight: 450, dob: "2020-06-12",
    registeredAt: daysAgo(600),
    baseline: { activity: 90, feeding: 89, movement: 88, rumination: 86 },
    current:  { activity: 30, feeding: 20, movement: 25, rumination: 15, tempTrend: "elevated", social: "recumbent" },
    lastObservation: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "MH-BUF-017", tagId: "MH-BUF-017", farmId: "FARM_D", speciesId: "SP_02", breedId: "BR_09",
    name: "Nandini", age: 4, sex: "Female", weight: 410, dob: "2022-08-20",
    registeredAt: daysAgo(420),
    baseline: { activity: 88, feeding: 86, movement: 87, rumination: 84 },
    current:  { activity: 85, feeding: 84, movement: 86, rumination: 82, tempTrend: "normal", social: "normal" },
    lastObservation: new Date(Date.now() - 7200000).toISOString(),
  },
  // Farm E — Sambhajinagar
  {
    id: "MH-CAT-089", tagId: "MH-CAT-089", farmId: "FARM_E", speciesId: "SP_01", breedId: "BR_07",
    name: "Surabhi", age: 3, sex: "Female", weight: 295, dob: "2023-06-01",
    registeredAt: daysAgo(290),
    baseline: { activity: 91, feeding: 88, movement: 89, rumination: 83 },
    current:  { activity: 89, feeding: 86, movement: 87, rumination: 81, tempTrend: "normal", social: "normal" },
    lastObservation: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "MH-BUF-022", tagId: "MH-BUF-022", farmId: "FARM_E", speciesId: "SP_02", breedId: "BR_11",
    name: "Shyama", age: 5, sex: "Female", weight: 440, dob: "2021-11-15",
    registeredAt: daysAgo(520),
    baseline: { activity: 87, feeding: 85, movement: 86, rumination: 83 },
    current:  { activity: 60, feeding: 58, movement: 62, rumination: 55, tempTrend: "elevated", social: "isolating" },
    lastObservation: new Date(Date.now() - 5400000).toISOString(),
  },
];

// ─── VACCINATIONS (pre-seeded) ───────────────────────────────────────────────
export const VACCINATIONS_SEED = [
  { id: "VAC_001", animalId: "MH-CAT-027", diseaseId: "DIS_01", vaccineName: "FMD Bivalent Vaccine", date: "2026-02-14", batchNo: "B2024-FMD-112", administeredBy: "Dr. A. Kulkarni", nextDue: "2026-08-14", status: "Overdue" },
  { id: "VAC_002", animalId: "MH-CAT-027", diseaseId: "DIS_02", vaccineName: "HS + BQ Combined", date: "2025-11-02", batchNo: "B2025-HSBQ-088", administeredBy: "Dr. A. Kulkarni", nextDue: "2026-11-02", status: "Current" },
  { id: "VAC_003", animalId: "MH-CAT-031", diseaseId: "DIS_01", vaccineName: "FMD Bivalent Vaccine", date: "2026-02-14", batchNo: "B2024-FMD-112", administeredBy: "Dr. A. Kulkarni", nextDue: "2026-08-14", status: "Overdue" },
  { id: "VAC_004", animalId: "MH-CAT-014", diseaseId: "DIS_01", vaccineName: "FMD Bivalent Vaccine", date: "2026-01-30", batchNo: "B2024-FMD-109", administeredBy: "Dr. A. Kulkarni", nextDue: "2026-07-30", status: "Overdue" },
  { id: "VAC_005", animalId: "MH-BUF-009", diseaseId: "DIS_03", vaccineName: "LSD Vaccine (Lumpi-ProVacInd)", date: "2025-12-05", batchNo: "B2025-LSD-044", administeredBy: "Dr. M. Shinde", nextDue: "2026-12-05", status: "Current" },
  { id: "VAC_006", animalId: "MH-GOT-102", diseaseId: "DIS_06", vaccineName: "PPR Vaccine (PPRV-SN-2009)", date: "2025-09-19", batchNo: "B2025-PPR-021", administeredBy: "Dr. A. Kulkarni", nextDue: "2026-09-19", status: "Current" },
  { id: "VAC_007", animalId: "MH-SHP-055", diseaseId: "DIS_06", vaccineName: "PPR Vaccine (PPRV-SN-2009)", date: "2025-09-19", batchNo: "B2025-PPR-021", administeredBy: "Dr. A. Kulkarni", nextDue: "2026-09-19", status: "Current" },
  { id: "VAC_008", animalId: "MH-CAT-063", diseaseId: "DIS_01", vaccineName: "FMD Bivalent Vaccine", date: "2026-02-01", batchNo: "B2024-FMD-110", administeredBy: "Dr. A. Kulkarni", nextDue: "2026-08-01", status: "Overdue" },
  { id: "VAC_009", animalId: "MH-CAT-078", diseaseId: "DIS_01", vaccineName: "FMD Bivalent Vaccine", date: "2026-02-01", batchNo: "B2024-FMD-110", administeredBy: "Dr. A. Kulkarni", nextDue: "2026-08-01", status: "Overdue" },
  { id: "VAC_010", animalId: "MH-BUF-017", diseaseId: "DIS_03", vaccineName: "LSD Vaccine (Lumpi-ProVacInd)", date: "2026-01-10", batchNo: "B2025-LSD-047", administeredBy: "Dr. M. Shinde", nextDue: "2027-01-10", status: "Current" },
  { id: "VAC_011", animalId: "MH-SHP-061", diseaseId: "DIS_06", vaccineName: "PPR Vaccine (PPRV-SN-2009)", date: "2025-09-19", batchNo: "B2025-PPR-021", administeredBy: "Dr. A. Kulkarni", nextDue: "2026-09-19", status: "Current" },
  { id: "VAC_012", animalId: "MH-CAT-089", diseaseId: "DIS_01", vaccineName: "FMD Bivalent Vaccine", date: "2026-03-20", batchNo: "B2024-FMD-118", administeredBy: "Field Officer T", nextDue: "2026-09-20", status: "Overdue" },
];

// ─── OBSERVATIONS (pre-seeded) ───────────────────────────────────────────────
export const OBSERVATIONS_SEED = [
  { id: "OBS_001", animalId: "MH-CAT-027", reportedBy: "R. Deshmukh", reporterRole: "farmer", timestamp: new Date(Date.now() - 7200000).toISOString(), symptoms: ["Not eating", "Limping"], notes: "Noticed she is not eating since morning. Also seems to be limping on the front leg.", severity: "Moderate", cameraSource: false, iotSource: false },
  { id: "OBS_002", animalId: "MH-BUF-009", reportedBy: "M. Rathi", reporterRole: "farmer", timestamp: new Date(Date.now() - 10800000).toISOString(), symptoms: ["Lying down", "Not eating", "High temperature"], notes: "Buffalo is lying down and not standing for over 4 hours. Breathing seems laboured.", severity: "Severe", cameraSource: true, iotSource: true },
  { id: "OBS_003", animalId: "MH-SHP-061", reportedBy: "A. Jadhav", reporterRole: "farmer", timestamp: new Date(Date.now() - 5400000).toISOString(), symptoms: ["Runny nose", "Not eating"], notes: "Sheep is not eating well and has runny nose.", severity: "Mild", cameraSource: false, iotSource: false },
  { id: "OBS_004", animalId: "MH-BUF-022", reportedBy: "V. Kadam", reporterRole: "farmer", timestamp: new Date(Date.now() - 5400000).toISOString(), symptoms: ["Low activity", "Fever"], notes: "Buffalo seems sluggish, temperature elevated on touch.", severity: "Moderate", cameraSource: false, iotSource: true },
];

// ─── ALERTS (pre-seeded) ─────────────────────────────────────────────────────
export const ALERTS_SEED = [
  { id: "AL_001", animalId: "MH-CAT-027", severity: "RED",      message: "Activity 43% below baseline; feeding 49% below baseline; elevated temperature trend; isolation behaviour.",       createdAt: new Date(Date.now() - 7200000).toISOString(),   status: "OPEN",         source: "ruleEngine" },
  { id: "AL_002", animalId: "MH-BUF-009", severity: "CRITICAL", message: "Activity 67% below baseline; feeding 78% below baseline; elevated temperature; recumbency detected.",            createdAt: new Date(Date.now() - 10800000).toISOString(),  status: "OPEN",         source: "ruleEngine" },
  { id: "AL_003", animalId: "MH-SHP-061", severity: "ORANGE",   message: "Activity 19% below baseline; feeding 18% below baseline; elevated temperature; isolation behaviour.",             createdAt: new Date(Date.now() - 5400000).toISOString(),   status: "OPEN",         source: "ruleEngine" },
  { id: "AL_004", animalId: "MH-CAT-078", severity: "YELLOW",   message: "Activity 27% below baseline; movement 24% below baseline — monitor closely.",                                     createdAt: new Date(Date.now() - 86400000).toISOString(),  status: "ACKNOWLEDGED", source: "ruleEngine" },
  { id: "AL_005", animalId: "MH-BUF-022", severity: "ORANGE",   message: "Activity 31% below baseline; feeding 32% below baseline; elevated temperature; isolation observed.",             createdAt: new Date(Date.now() - 5400000).toISOString(),   status: "OPEN",         source: "ruleEngine" },
  { id: "AL_006", animalId: "MH-GOT-102", severity: "YELLOW",   message: "Activity 23% below baseline; feeding 24% below baseline — field verification recommended.",                       createdAt: new Date(Date.now() - 21600000).toISOString(),  status: "OPEN",         source: "ruleEngine" },
];

// ─── CASES (pre-seeded) ──────────────────────────────────────────────────────
export const CASES_SEED = [
  {
    id: "CASE_001", animalId: "MH-BUF-009", alertId: "AL_002",
    stage: "Field Review", suspectedDiseaseId: "DIS_02",
    clinicalObservations: "Animal recumbent. Throat swelling noted. Profuse salivation. High fever.",
    sampleId: null, sampleType: null, collectionDate: null,
    laboratory: null, labResult: null, labResultDate: null,
    notes: "Haemorrhagic Septicaemia suspected. Monsoon risk high.", action: null,
    followUpDate: null, outcome: null,
    openedAt: new Date(Date.now() - 10800000).toISOString(),
    assignedVet: "Dr. M. Shinde",
  },
  {
    id: "CASE_002", animalId: "MH-CAT-027", alertId: "AL_001",
    stage: "Accepted", suspectedDiseaseId: "DIS_01",
    clinicalObservations: null,
    sampleId: null, sampleType: null, collectionDate: null,
    laboratory: null, labResult: null, labResultDate: null,
    notes: "FMD suspected. Will conduct field review tomorrow.", action: null,
    followUpDate: null, outcome: null,
    openedAt: new Date(Date.now() - 7200000).toISOString(),
    assignedVet: "Dr. A. Kulkarni",
  },
];

// ─── LAB SAMPLES (pre-seeded) ────────────────────────────────────────────────
export const LAB_SAMPLES_SEED = [
  {
    id: "SMP_001", caseId: "CASE_001", animalId: "MH-BUF-009",
    sampleType: "Blood / Serum", sampleId: "SMP-8841",
    test: "Bacterial culture & sensitivity",
    laboratory: "Regional Disease Diagnostic Laboratory, Nagpur",
    collectionDate: daysAgo(1),
    submittedDate: daysAgo(1),
    result: "Pending",
    suspectedDiseaseId: "DIS_02",
    collectedBy: "Dr. M. Shinde",
  },
];

// ─── EXPOSURE EVENTS (pre-seeded) ────────────────────────────────────────────
export const EXPOSURE_EVENTS_SEED = [
  { id: "EXP_001", sourceId: "MH-BUF-009", targetId: "MH-BUF-017", distance: 3.2, contacts: 4, duration: 20, lastContact: new Date(Date.now() - 7200000).toISOString(), riskLevel: "HIGH",   diseaseId: "DIS_02" },
  { id: "EXP_002", sourceId: "MH-CAT-027", targetId: "MH-CAT-031",  distance: 4.2, contacts: 6, duration: 18, lastContact: new Date(Date.now() - 2400000).toISOString(), riskLevel: "HIGH",   diseaseId: "DIS_01" },
  { id: "EXP_003", sourceId: "MH-CAT-027", targetId: "MH-CAT-014",  distance: 9.1, contacts: 2, duration: 5,  lastContact: new Date(Date.now() - 10800000).toISOString(),riskLevel: "MEDIUM", diseaseId: "DIS_01" },
  { id: "EXP_004", sourceId: "MH-SHP-061", targetId: "MH-SHP-055",  distance: 2.8, contacts: 8, duration: 30, lastContact: new Date(Date.now() - 3600000).toISOString(), riskLevel: "HIGH",   diseaseId: "DIS_06" },
];

// ─── DISTRICTS ────────────────────────────────────────────────────────────────
export const DISTRICTS_SEED = [
  { id: "Nashik",             lat: 20.01, lng: 73.79 },
  { id: "Pune",               lat: 18.52, lng: 73.86 },
  { id: "Kolhapur",           lat: 16.70, lng: 74.24 },
  { id: "Nagpur",             lat: 21.14, lng: 79.09 },
  { id: "Chh. Sambhajinagar", lat: 19.88, lng: 75.34 },
  { id: "Amravati",           lat: 20.93, lng: 77.75 },
  { id: "Solapur",            lat: 17.68, lng: 75.91 },
  { id: "Thane",              lat: 19.21, lng: 72.97 },
];

// ─── CONTAINMENT ZONES ────────────────────────────────────────────────────────
export const CONTAINMENT_ZONES_SEED = [];

// ─── AUDIT LOG ────────────────────────────────────────────────────────────────
export const AUDIT_LOG_SEED = [
  { id: "AUD_001", action: "CASE_OPENED",   entityId: "CASE_001", userId: "USR_04", timestamp: new Date(Date.now() - 10800000).toISOString(), detail: "Case opened for MH-BUF-009; suspected HS" },
  { id: "AUD_002", action: "SAMPLE_ADDED",  entityId: "SMP_001",  userId: "USR_04", timestamp: new Date(Date.now() - 9000000).toISOString(),  detail: "Blood sample collected for CASE_001" },
  { id: "AUD_003", action: "ALERT_CREATED", entityId: "AL_001",   userId: "SYSTEM", timestamp: new Date(Date.now() - 7200000).toISOString(),  detail: "RED alert auto-generated for MH-CAT-027" },
  { id: "AUD_004", action: "CASE_OPENED",   entityId: "CASE_002", userId: "USR_03", timestamp: new Date(Date.now() - 7200000).toISOString(),  detail: "Case opened for MH-CAT-027; suspected FMD" },
];
